version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: spotify_db
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify123
      POSTGRES_DB: spotify_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spotify -d spotify_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      postgres:
        condition: service_healthy  # This is the magic line!
    ports:
      - "8981:8981"
    environment:
      DATABASE_URL: postgresql://spotify:spotify123@postgres:5432/spotify_db
      SECRET_KEY: mysecretkey

volumes:
  postgres_data: # Defined the volume here